name: Build and deploy (production)

on:
  release: 
    types: [published]

env:
  RELEASE_NAME: data-api
  CHART_VALUES_FILE: .helm/values.prod.yml
  DEPLOY_NAMESPACE: sledilnik-prod
  DEPLOY_ENV: production
  DEPLOY_URL: https://api.sledilnik.org
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build and push docker container image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./sources/SloCovidServer
          file: ./sources/SloCovidServer/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/data-api:${{ env.IMAGE_TAG}}

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy
        uses: sledilnik/action-helm-deploy@master
        with:
          chartName: sledilnik/data-api
          chartVersion: '1.0.2'
          kubeconfig: '${{ secrets.KUBECONFIG }}'        